name: Build to Docker Hub and Deploy to EKS
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        docker build -t crud-user .
        docker tag crud-user agungw9/crud-user
        docker logout
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push agungw9/crud-user
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Deploy to EKS
      uses: aws/eks-deploy-action@v1
      with:
        cluster-name: my-cluster
        configuration-file-path: k8s/deployment.yml
        image-tag: latest
        image-repository: agungw9/crud-user
